CREATE ROLE '${SERVER_USER}' LOGIN PASSWORD '${ADMIN_ROLE_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE '${DATABASE}' TO '${SERVER_USER}';
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION ${SERVER_USER};
